[2024-08-19T20:56:55.071+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-19T20:56:55.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-08-19T20:56:55.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-08-19T20:56:55.097+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-19T20:56:55.105+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-08-18 00:00:00+00:00
[2024-08-19T20:56:55.111+0000] {standard_task_runner.py:64} INFO - Started process 59 to run task
[2024-08-19T20:56:55.115+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-08-18T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpzi9vpga1']
[2024-08-19T20:56:55.119+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask s3_upload
[2024-08-19T20:56:55.189+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-08-18T00:00:00+00:00 [running]> on host 4e5e09b43ee4
[2024-08-19T20:56:55.457+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dinesh Saraswat' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-18T00:00:00+00:00'
[2024-08-19T20:56:55.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-19T20:56:55.508+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-19T20:56:55.509+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 5, in upload_s3_pipeline
    file_path = ti.xcom_pull(task_id = 'reddit_extraction', key='return_value')
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2024-08-19T20:56:55.526+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=scheduled__2024-08-18T00:00:00+00:00, execution_date=20240818T000000, start_date=20240819T205655, end_date=20240819T205655
[2024-08-19T20:56:55.585+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task s3_upload (xcom_pull() got an unexpected keyword argument 'task_id'; 59)
[2024-08-19T20:56:55.711+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-19T20:56:55.779+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-19T20:56:55.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
